Tue 14 Nov 2023 16:46:30 reorganize_data.py ERROR:An error occurred: [Errno 2] No such file or directory: 'DELL_NB.xlsx'
Traceback (most recent call last):
  File "/Users/yidechiu/Desktop/chiu/code/tech_info_push/reorganize_data.py", line 23, in <module>
    df = pd.read_excel("DELL_NB.xlsx",index_col=0)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yidechiu/Desktop/chiu/code/tech_info_push/.venv/lib/python3.11/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yidechiu/Desktop/chiu/code/tech_info_push/.venv/lib/python3.11/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yidechiu/Desktop/chiu/code/tech_info_push/.venv/lib/python3.11/site-packages/pandas/io/excel/_base.py", line 482, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yidechiu/Desktop/chiu/code/tech_info_push/.venv/lib/python3.11/site-packages/pandas/io/excel/_base.py", line 1652, in __init__
    ext = inspect_excel_format(
          ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yidechiu/Desktop/chiu/code/tech_info_push/.venv/lib/python3.11/site-packages/pandas/io/excel/_base.py", line 1525, in inspect_excel_format
    with get_handle(
         ^^^^^^^^^^^
  File "/Users/yidechiu/Desktop/chiu/code/tech_info_push/.venv/lib/python3.11/site-packages/pandas/io/common.py", line 865, in get_handle
    handle = open(handle, ioargs.mode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'DELL_NB.xlsx'
